version: "3"

services:
  mongo:
    container_name: local-mongo
    image: mongo:6.0.8
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongodb:/data/db
